### ISSUE TITLE
An int-init-related issue

### ISSUE THREAD

**Issue by xxuurruuii** [Noobly-Walker/expol.py#1]
>a=expol('0e0')
>b=expol(0)
>a+b
  File "expol.py", line 135, in __add__
    elif expDiff >= 0: mantOut = var1[MANTISSA]+var2[MANTISSA]/10**expDiff
TypeError: unsupported operand type(s) for +: 'decimal.Decimal' and 'float'

**Comment by Noobly-Walker** [comment]
It seems like it's already fixed. I'll push the patched code.
